/* Generated by AN DISI Unibo */ 
package it.unibo.flipflopmock

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Flipflopmock ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						delay(1000) 
						CommUtils.outmagenta("$name STARTS")
						request("state", "state(0,0)" ,"flipflop" )  
						delay(1000) 
						request("state", "state(1,0)" ,"flipflop" )  
						delay(1000) 
						request("state", "state(0,1)" ,"flipflop" )  
						delay(1000) 
						request("state", "state(0,0)" ,"flipflop" )  
						delay(1000) 
						request("state", "state(1,0)" ,"flipflop" )  
						delay(1000) 
						request("state", "state(0,1)" ,"flipflop" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
