/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package _prodcons;

import _prodcons.tcp.ConsumerServer;
import _prodcons.tcp.Producer;
import java.lang.Thread;

public class App {
    public static void main(String[] args) {
        Thread server = new Thread(new ConsumerServer(3333));

        server.start();

        System.out.println("Initializing producers");

        Thread[] producers = new Thread[] {
                new Thread(new Producer("127.0.0.1", 3333)),
                new Thread(new Producer("127.0.0.1", 3333)),
                new Thread(new Producer("127.0.0.1", 3333)),
        };

        for (Thread producer : producers) {
            try {
                System.out.println("Starting producer " + producer.getId());
                producer.start();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
}
