/* Generated by AN DISI Unibo */ 
package it.unibo.cleaner24

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024
import main.resources.robotvirtual.VrobotLLMoves24
import main.resources.map.MovementTracker

class Cleaner24 ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "activate"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		 val vr = VrobotLLMoves24.create("localhost",myself)
		
			var GoingDown   = true 
			var tracker = MovementTracker(0, 0);
		return { //this:ActionBasciFsm
				state("activate") { //this:State
					action { //it:State
						  GoingDown = true  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="coverColumn", cond=doswitch() )
				}	 
				state("coverColumn") { //this:State
					action { //it:State
						delay(300) 
						 var RSTEP = vr.step(350)  
						if(  RSTEP  
						 ){forward("stepdone", "stepdone(1)" ,name ) 
						}
						else
						 {forward("stepfail", "stepfail(1)" ,name ) 
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="coverColumn",cond=whenDispatch("stepdone"))
					transition(edgeName="t01",targetState="turn",cond=whenDispatch("stepfail"))
				}	 
				state("turn") { //this:State
					action { //it:State
						CommUtils.outblack("turn while GoingDown=$GoingDown")
						if(  GoingDown  
						 ){ vr.backward(50)   
						 vr.turnLeft()     
						}
						else
						 { vr.turnRight()  
						 }
						delay(300) 
						 var RSTEP = vr.step(350)  
						if(  RSTEP  
						 ){forward("stepdone", "stepdone(1)" ,name ) 
						}
						else
						 {forward("stepfail", "stepfail(1)" ,name ) 
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t02",targetState="stepAfterTurn",cond=whenDispatch("stepdone"))
					transition(edgeName="t03",targetState="lastColumn",cond=whenDispatch("stepfail"))
				}	 
				state("stepAfterTurn") { //this:State
					action { //it:State
						CommUtils.outmagenta("stepAfterTurn while GoingDown=$GoingDown")
						if(  GoingDown  
						 ){ vr.turnLeft()    
						}
						else
						 { vr.turnRight()  
						 }
						delay(300) 
						  GoingDown = ! GoingDown  
						 var RSTEP = vr.step(350)  
						if(  RSTEP  
						 ){forward("stepdone", "stepdone(1)" ,name ) 
						}
						else
						 {forward("stepfail", "stepfail(1)" ,name ) 
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t04",targetState="coverColumn",cond=whenDispatch("stepdone"))
					transition(edgeName="t05",targetState="lastColumn",cond=whenDispatch("stepfail"))
				}	 
				state("lastColumn") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if(  GoingDown  
						 ){ vr.turnLeft()     
						}
						else
						 { vr.turnRight()  
						 }
						 var RSTEP = vr.step(350)  
						if(  RSTEP  
						 ){forward("stepdone", "stepdone(1)" ,name ) 
						}
						else
						 {forward("stepfail", "stepfail(1)" ,name ) 
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t06",targetState="coverLastColumn",cond=whenDispatch("stepdone"))
					transition(edgeName="t07",targetState="endofwork",cond=whenDispatch("stepfail"))
				}	 
				state("coverLastColumn") { //this:State
					action { //it:State
						CommUtils.outyellow("coverLastColumn norobot")
						delay(200) 
						 var RSTEP = vr.step(350)  
						if(  RSTEP  
						 ){forward("stepdone", "stepdone(1)" ,name ) 
						}
						else
						 {forward("stepfail", "stepfail(1)" ,name ) 
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t08",targetState="coverLastColumn",cond=whenDispatch("stepdone"))
					transition(edgeName="t09",targetState="endofwork",cond=whenDispatch("stepfail"))
				}	 
				state("endofwork") { //this:State
					action { //it:State
						CommUtils.outblue("---------------------------")
						 tracker.saveRoomMap("mapcleaned")  
						 System.exit(0)  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("fatalError") { //this:State
					action { //it:State
						CommUtils.outred("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
